{tmplinclude file="header.phtml"}

{if $user->getPrivs() eq 3}
    <ul class="breadcrumb">
        <li>
            <a href="{genUrl}">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="{genUrl controller="statistics" action="public"}">Public Traffic Statistics</a> <span class="divider">/</span>
        </li>
        <li class="active">
            {$graphs.$graph.title} :: {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}
        </li>
    </ul>
    <div class="page-content">
{else}
    <div class="page-content">
        <div class="page-header">
            <h1>Public Traffic Statistics</h1>
        </div>
{/if}


{OSS_Message}

<h3>{$graphs.$graph.title} :: {foreach from=$categories key=cname item=cvalue}{if $category eq $cvalue}{$cname}{/if}{/foreach}</h3>
<p>
<form action="{genUrl controller="statistics" action="public"}" method="post" class="form-horizontal">
<table>
<tr>
    <td width="20"></td>
    <td valign="middle"><strong>Select {if $multiIXP}IXP / {/if}Infrastructure:&nbsp;</strong></td>
    <td>
        <select name="graph" class="chzn-select" onchange="this.form.submit();">
            {foreach $graphs as $id => $data}
                <option value="{$id}" {if $graph eq $id}selected{/if}>{$data.title}</option>
            {/foreach}
        </select>
    </td>
    <td width="20"></td>
    <td valign="middle"><strong>Category:&nbsp;</strong></td>
    <td>
        <select name="category" class="chzn-select" onchange="this.form.submit();">
            {foreach from=$categories key=cname item=cval}
                <option value="{$cval}" {if $category eq $cval}selected{/if}>{$cname}</option>
            {/foreach}
        </select>
    </td>
</tr>
</table>
</form>
</p>

<div class="row-fluid">

{assign var='count' value=0}

{foreach from=$periods key=pname item=pvalue}

    <div class="span6">

        <div class="well">
            <h3>{$pname} Graph</h3>

            <p>
                {genMrtgGraphBox
                        shortname='X_Peering'
                        period=$pvalue
                        category=$category
                        values=$stats.$pvalue
                        graph=$graphs.$graph.name
                }
            </p>
        </div>
    </div>

    {assign var='count' value=$count+1}

    {if $count%2 eq 0}
        </div><br /><div class="row-fluid">
    {/if}

{/foreach}

{if $count%2 neq 0}
    <div class="span3"></div>
{/if}

</div>

</div>

{tmplinclude file="footer.phtml"}

